-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/ZynqBF_2tx_fpga/ZynqBF_2t_ip_src_ZynqBF_2tx_fpga.vhd
-- Created: 2019-01-15 11:04:35
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ZynqBF_2t_ip_src_ZynqBF_2tx_fpga
-- Source Path: ZynqBF_2tx_fpga
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ZynqBF_2t_ip_src_ZynqBF_2tx_fpga IS
  PORT( rx_i_in                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        rx_q_in                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        rx_v_in                           :   IN    std_logic;
        rx_i_out                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        rx_q_out                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        rx_v_out                          :   OUT   std_logic;
        ch1_i                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        ch1_q                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        ch2_i                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        ch2_q                             :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END ZynqBF_2t_ip_src_ZynqBF_2tx_fpga;


ARCHITECTURE rtl OF ZynqBF_2t_ip_src_ZynqBF_2tx_fpga IS

  -- Signals
  SIGNAL Constant_out1                    : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Constant1_out1                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Constant2_out1                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Constant3_out1                   : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  Constant_out1 <= to_signed(16#7FFF#, 16);

  ch1_i <= std_logic_vector(Constant_out1);

  Constant1_out1 <= to_signed(16#7FFF#, 16);

  ch1_q <= std_logic_vector(Constant1_out1);

  Constant2_out1 <= to_signed(16#7FFF#, 16);

  ch2_i <= std_logic_vector(Constant2_out1);

  Constant3_out1 <= to_signed(16#7FFF#, 16);

  ch2_q <= std_logic_vector(Constant3_out1);

  rx_i_out <= rx_i_in;

  rx_q_out <= rx_q_in;

  rx_v_out <= rx_v_in;

END rtl;

