vlib work
vcom  ZynqBF_2tx_fpga_pkg.vhd
vcom  goldSequences.vhd
vcom  gs_selector.vhd
vcom  correlation_config.vhd
vcom  correlator_en.vhd
vcom  data_in.vhd
vcom  gold_sequences.vhd
vcom  get_bit.vhd
vcom  SimpleDualPortRAM_generic.vhd
vcom  rx_ram_i.vhd
vcom  all_u.vhd
vcom  shift_rx.vhd
vcom  correlator_i.vhd
vcom  sum_elements_i.vhd
vcom  correlator1.vhd
vcom  peak_fsm.vhd
vcom  running_max.vhd
vcom  store_index.vhd
vcom  peakdetect_ch1.vhd
vcom  select_inputs.vhd
vcom  ram_rd_counter.vhd
vcom  ram_counter.vhd
vcom  correlation_config_block.vhd
vcom  correlator_en_block.vhd
vcom  data_in_block.vhd
vcom  gold_sequences_block.vhd
vcom  correlator2.vhd
vcom  peak_fsm_block.vhd
vcom  running_max_block.vhd
vcom  store_index_block.vhd
vcom  peakdetect_ch2.vhd
vcom  state_machine.vhd
vcom  rx_i_fifo.vhd
vcom  rx_q_fifo.vhd
vcom  in_fifo.vhd
vcom  rx_bram.vhd
vcom  Detect_Change.vhd
vcom  HDL_Reciprocal_core.vhd
vcom  HDL_Reciprocal.vhd
vcom  calc_inverse.vhd
vcom  local_fsm.vhd
vcom  update_csi.vhd
vcom  select_inputs_block.vhd
vcom  ch_est.vhd
vcom  channel_estimator.vhd
vcom  ZynqBF_2tx_fpga_tc.vhd
vcom  ZynqBF_2tx_fpga.vhd
